# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # 定义多个虚拟机配置.
  vms = [
    { name: "ubuntu", ip: "192.168.1.110" },
    # { name: "windows", ip: "192.168.1.111", box: "gusztavvargadr/windows-11" },
  ]

  config.vm.box_check_update = false
  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
  end

  ubuntu = <<-SHELL
echo ========== 去除提示页 ==========
sudo apt purge -y needrestart
echo ========== 更换阿里源 ==========
sudo sed -i -E 's#http://(archive|security).ubuntu.com#http://mirrors.aliyun.com#g' /etc/apt/sources.list
# cloud-init 之后会替换源，所以把它的也换掉.
sudo sed -i -E 's#http://(archive|security).ubuntu.com#http://mirrors.aliyun.com#g' /etc/cloud/cloud.cfg
echo ========== 移除无用包 ==========
sudo apt autoremove -y
echo ========== 更新软件包 ==========
sudo apt update
echo ========== 改系统时区 ==========
sudo cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
sudo timedatectl set-timezone Asia/Shanghai
echo ========== 安装 Docker ==========
sudo apt install -y docker.io
sudo mkdir -p /etc/docker
cat <<EOF | sudo tee /etc/docker/daemon.json
{
  "registry-mirrors": ["https://registry.cn-hangzhou.aliyuncs.com"]
}
EOF
sudo sed -i '/ExecStart=/s/$/ -H tcp:\/\/0.0.0.0:2375/' /usr/lib/systemd/system/docker.service
sudo systemctl daemon-reload
sudo systemctl restart docker
echo ========== 安装 docker-compose ==========
sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
SHELL

  vms.each do |vm|
    config.vm.define "#{vm[:name]}" do |item|
      if vm.key?(:box) && !vm[:box].nil?
        item.vm.box = vm[:box]
      else
        item.vm.box = "ubuntu/jammy64"
        item.vm.provision "shell", inline: ubuntu
      end

      item.vm.hostname = vm[:name]
      item.vm.network "public_network", ip: vm[:ip]
      item.vm.synced_folder ".", "/www/wwwroot"

      item.vm.provider "virtualbox" do |vb|
        # vb.gui = true
        vb.name = vm[:name]
        vb.cpus = 4
        vb.memory = "8192"
      end
    end
  end
end
